[workspace]
members = [
    "bin/icp-cli",
    "lib/icp-adapter",
    "lib/icp-canister",
    "lib/icp-fs",
    "lib/icp-identity",
    "lib/icp-network",
    "lib/icp-project",
]

resolver = "3"

[workspace.dependencies]
async-trait = "0.1.88"
camino = { version = "1.1.9", features = ["serde1"] }
candid = "0.10.14"
fd-lock = "4.0.4"
glob = "0.3.2"
hex = "0.4.3"
ic-agent = { version = "0.40.1" }
pocket-ic = "9.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
snafu = "0.8.5"
tempfile = "3"
time = "0.3.9"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.16.0", features = ["serde", "v4"] }

[workspace.dependencies.reqwest]
version = "0.12.15"
default-features = false
features = ["rustls-tls"]
