[workspace]
members = [
    "bin/icp-cli",
    "lib/icp-identity",
    "lib/icp-network",
    "lib/icp-support"
]

resolver = "3"

[workspace.dependencies]
candid = "0.10.14"
directories = "6.0.0"
fd-lock = "4.0.4"
hex = "0.4.3"
ic-agent = { version = "0.40.1" }
pocket-ic = "9.0.0"
reqwest = { version = "0.12.15", default-features = false, features = [
    "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.8.5"
sysinfo = "0.34.2"
tempfile = "3"
time = "0.3.9"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.16.0", features = ["serde", "v4"] }
