[workspace]
members = [
    "bin/icp-cli",
    "lib/icp-identity",
    "lib/icp-network",
    "lib/icp-support"
]

resolver = "3"

[workspace.dependencies]
directories = "6.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.34.2"
thiserror = "2"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.16.0", features = ["serde", "v4"] }
