[workspace]
members = ["bin/icp-cli", "lib/icp-dirs", "lib/icp-identity", "lib/icp-network"]

resolver = "3"

[workspace.dependencies]
bip32 = "0.5.0"
camino = { version = "1.1.9", features = ["serde1"] }
clap = { version = "4.5.3", features = ["derive"] }
dialoguer = "0.11.0"
directories = "6.0.0"
ed25519-consensus = "2.1.0"
elliptic-curve = { version = "0.13.8", features = ["sec1", "std", "pkcs8"] }
ic-agent = "0.40.0"
icp-dirs = { path = "lib/icp-dirs" }
icp-identity = { path = "lib/icp-identity" }
icp-network = { path = "lib/icp-network" }
itertools = "0.14.0"
k256 = { version = "0.13.4", features = ["pem", "pkcs8", "std"] }
p256 = { version = "0.13.2", features = ["pem", "pkcs8", "std"] }
parse-display = "0.10.0"
pem = "3.0.5"
pkcs8 = { version = "0.10.2", features = ["encryption", "std"] }
rand = "0.9.1"
sec1 = { version = "0.7.3", features = ["pkcs8"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
snafu = "0.8.5"
tiny-bip39 = "2.0.0"
zeroize = "1.8.1"

[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
enum_variant_names = "allow"
