disallowed-types = [
    { path = "std::path::PathBuf", reason = "Use `use icp::prelude::PathBuf;` or `use icp::prelude::*;` instead" },
    { path = "std::path::Path", reason = "Use `icp::prelude::Path;` or `use icp::prelude::*;` instead" },
]
