[package]
name = "icp"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
