[package]
name = "schema-gen"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
icp = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
