[advisories]
ignore = [
  "RUSTSEC-2025-0140", # gix-date UTF-8 contract issue dependency of cargo-generate
  "RUSTSEC-2026-0001", # rkyv undefined behavior on OOM dependency of byte-unit

  # Unmaintained crates (transitive dependencies)
  "RUSTSEC-2021-0127", # serde_cbor - dependency of ic-agent/ic-transport-types
  "RUSTSEC-2024-0384", # instant - dependency of backoff, cached, parking_lot, rhai
  "RUSTSEC-2024-0388", # derivative - dependency of ic-asset
  "RUSTSEC-2024-0436", # paste - dependency of candid, cargo-generate
  "RUSTSEC-2025-0012", # backoff - dependency of ic-agent, ic-asset
]
informational_warnings = ["unsound", "notice"] # default minus "unmaintained"
