[package]
name = "icp-canister-interfaces"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }


[dependencies]
bigdecimal = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }

[dev-dependencies]

