[package]
name = "icp-canister-interfaces"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
bigdecimal = { workspace = true }
candid = { workspace = true }
serde = { workspace = true }

[dev-dependencies]

