[package]
name = "icp-cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "icp"
path = "src/main.rs"

[dependencies]
camino = { workspace = true }
clap = { version = "4.5.35", features = ["derive"] }
icp-canister = { path = "../../lib/icp-canister" }
icp-fs = { path = "../../lib/icp-fs" }
icp-network = { path = "../../lib/icp-network" }
icp-project = { path = "../../lib/icp-project" }
snafu = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
reqwest = { workspace = true }
camino-tempfile = "1"
