[package]
name = "icp-cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "icp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
icp-network = { path = "../../lib/icp-network" }
icp-fs = { path = "../../lib/icp-fs" }
snafu = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
reqwest = { workspace = true }
tempfile = "3"
