name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .
  # Disable DFX telemetry
  DFX_TELEMETRY: "off"

jobs:

  # Check that the project compiles before we do anything else
  # we take this opportunity to build a cache
  # only do ubuntu  because that's what most of the other jobs will
  # run on
  check-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: build
        run: cargo build
        env:
          RUST_BACKTRACE: 1

  #
  # Run the linter
  # 
  lint:
    needs: check-compile
    name: lint:required
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Lint
        run: cargo clippy --verbose --tests --benches -- -D warnings -D clippy::all
        env:
          RUST_BACKTRACE: 1

  #
  # Check formatting 
  # 
  format:
    needs: check-compile
    name: fmt:required
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain from rust-toolchain.toml
        run: rustup show

      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

  #
  # Check that the cli reference docs have been generated
  #
  cli-ref:
    needs: check-compile
    name: cli-ref:required
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: generate docs
        run: ./scripts/generate-cli-docs.sh

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ The cli-reference documentation is not up to date"
            echo ""
            echo " Run ./scripts/generate-cli-docs.sh to update them"
            echo ""
            git status --porcelain
            exit 1
          else
            echo "✅ Git state is clean."
          fi

  #
  # Check that the cli reference docs have been generated
  #
  icp-yaml-schema:
    needs: check-compile
    name: icp-yaml-schema:required
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust toolchain
        run: rustup show

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: generate icp.yaml schema
        run: ./scripts/generate-config-schema.sh

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ The icp.yaml schema is not up to date"
            echo ""
            echo " Run ./scripts/generate-config-schema.sh to update them"
            echo ""
            git status --porcelain
            exit 1
          else
            echo "✅ Git state is clean."
          fi

  ########################################################################
  # Run the test matrix
  ########################################################################

  discover:
    # Don't run this until we've been able to compile so we can reuse the cache
    needs: check-compile
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(python3 .github/scripts/test-matrix.py)" >> $GITHUB_OUTPUT

  unit-tests:
    needs: check-compile
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      # We would have only built the cache for ubuntu in `check-compile`
      # so we have to use cache instead of cache/restore
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run unit tests
        run: cargo test --workspace --lib --bins

  test:
    name: ${{ matrix.test }} on ${{ matrix.os }}
    needs: discover
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.discover.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust toolchain version
        run: rustup show

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Set up path to dfx for tests and to pocketic for icp
        run: |
          dfx cache install
          echo "ICPTEST_DFX_PATH=$(dfx cache show)/dfx" >> "$GITHUB_ENV"
          echo "ICP_POCKET_IC_PATH=$(dfx cache show)/pocket-ic" >> "$GITHUB_ENV"

      - name: Run ${{ matrix.test }}
        run: cargo test --test ${{ matrix.test }}

  aggregate:
    name: test:required
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [unit-tests, test]
    steps:
      - name: check result
        if: ${{ needs.unit-tests.result != 'success' || needs.test.result != 'success' }}
        run: exit 1
