name: Documentation Updated
#
# Runs a series of checks to make sure that all the docs
# that need to be generated have been genrated an are up
# to date.
#
# For now we generate:
# - the cli reference
# - the json schema for icp.yaml
#
on:
  push:
    branches:
      - main
  pull_request:

jobs:

  cli-ref:
    name: cli-ref:required
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust toolchain
        run: rustup show

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: generate docs
        run: ./scripts/generate-cli-docs.sh

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ The cli-reference documentation is not up to date"
            echo ""
            echo " Run ./scripts/generate-cli-docs.sh to update them"
            echo ""
            git status --porcelain
            exit 1
          else
            echo "✅ Git state is clean."
          fi

  icp-yaml-schema:
    name: icp-yaml-schema:required
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust toolchain
        run: rustup show

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: generate icp.yaml schema
        run: ./scripts/generate-config-schema.sh

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "❌ The icp.yaml schema is not up to date"
            echo ""
            echo " Run ./scripts/generate-config-schema.sh to update them"
            echo ""
            git status --porcelain
            exit 1
          else
            echo "✅ Git state is clean."
          fi
