name: Lint

on:
  push:
    branches:
      - main
      - ens/sdk-2108-local-network
  pull_request:

jobs:
  lint:
    name: lint:required
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust toolchain
        run: rustup show

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-lint-1

      - name: Run Lint
        run: cargo clippy --verbose --tests --benches -- -D warnings
        env:
          RUST_BACKTRACE: 1
