name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .
  # Disable DFX telemetry
  DFX_TELEMETRY: "off"

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(python3 .github/scripts/test-matrix.py)" >> $GITHUB_OUTPUT

  unit-tests:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust toolchain version
        run: rustup show

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run unit tests
        run: cargo test --workspace --lib --bins

  test:
    name: ${{ matrix.test }} on ${{ matrix.os }}
    needs: discover
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.discover.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4

      - name: Show Rust toolchain version
        run: rustup show

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Set up path to dfx for tests
        run: |
          dfx cache install
          echo "ICPTEST_DFX_PATH=$(dfx cache show)/dfx" >> "$GITHUB_ENV"

      - name: install pocket-ic
        run: |
          URL="https://github.com/dfinity/pocketic/releases/download/10.0.0/pocket-ic-x86_64-linux.gz"
          DEST="/usr/local/bin/pocket-ic"

          curl -L "$URL" -o pocket-ic.gz
          gunzip -f pocket-ic.gz
          chmod +x pocket-ic
          sudo mv pocket-ic "$DEST"

          echo "Installed pocket-ic to $DEST"
          echo "ICP_POCKET_IC_PATH=$DEST" >> "$GITHUB_ENV"

      - name: Run ${{ matrix.test }}
        run: cargo test --test ${{ matrix.test }}

  aggregate:
    name: test:required
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [unit-tests, test]
    steps:
      - name: check result
        if: ${{ needs.unit-tests.result != 'success' || needs.test.result != 'success' }}
        run: exit 1
