[package]
name = "icp-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
icp = { workspace = true }
fd-lock = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
snafu = { workspace = true }
